# Generated by Django 5.1.3 on 2024-11-16 20:57

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_confirmed",
                    models.BooleanField(
                        default=True, verbose_name="Potwierdzony email"
                    ),
                ),
                (
                    "contributed",
                    models.BooleanField(default=False, verbose_name="Zrobił wpis"),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("K", "Kobieta"), ("M", "Mężczyzna")],
                        default=None,
                        max_length=1,
                        null=True,
                        verbose_name="płeć",
                    ),
                ),
                (
                    "career_start_year",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (2024, 2024),
                            (2023, 2023),
                            (2022, 2022),
                            (2021, 2021),
                            (2020, 2020),
                            (2019, 2019),
                            (2018, 2018),
                            (2017, 2017),
                            (2016, 2016),
                            (2015, 2015),
                            (2014, 2014),
                            (2013, 2013),
                            (2012, 2012),
                            (2011, 2011),
                            (2010, 2010),
                            (2009, 2009),
                            (2008, 2008),
                            (2007, 2007),
                            (2006, 2006),
                            (2005, 2005),
                            (2004, 2004),
                            (2003, 2003),
                            (2002, 2002),
                            (2001, 2001),
                            (2000, 2000),
                            (1999, 1999),
                            (1998, 1998),
                            (1997, 1997),
                            (1996, 1996),
                            (1995, 1995),
                            (1994, 1994),
                            (1993, 1993),
                            (1992, 1992),
                            (1991, 1991),
                            (1990, 1990),
                            (1989, 1989),
                            (1988, 1988),
                            (1987, 1987),
                            (1986, 1986),
                            (1985, 1985),
                            (1984, 1984),
                            (1983, 1983),
                            (1982, 1982),
                            (1981, 1981),
                            (1980, 1980),
                            (1979, 1979),
                            (1978, 1978),
                            (1977, 1977),
                            (1976, 1976),
                            (1975, 1975),
                            (1974, 1974),
                            (1973, 1973),
                            (1972, 1972),
                            (1971, 1971),
                            (1970, 1970),
                            (1969, 1969),
                            (1968, 1968),
                            (1967, 1967),
                            (1966, 1966),
                            (1965, 1965),
                            (1964, 1964),
                            (1963, 1963),
                            (1962, 1962),
                            (1961, 1961),
                            (1960, 1960),
                        ],
                        null=True,
                        verbose_name="rok rozpoczęcia kariery",
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "wyższe"),
                            ("A0", "student"),
                            ("A1", "MBA"),
                            ("A2", "stopień naukowy"),
                            ("A3", "inne podyplomowe"),
                            ("B", "średnie"),
                            ("C", "gimnazjalne"),
                            ("D", "zasadnicze"),
                            ("E", "podstawowe"),
                        ],
                        default=None,
                        max_length=2,
                        null=True,
                        verbose_name="wykształcenie",
                    ),
                ),
                ("linkedin_id", models.CharField(blank=True, max_length=10, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil",
                "verbose_name_plural": "Profil",
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, editable=False, null=True, unpack_ipv4=True
                    ),
                ),
                ("path", models.CharField(editable=False, max_length=200)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
            ],
            options={
                "verbose_name": "Wizyta",
                "verbose_name_plural": "Wizyty",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="visited_companies",
            field=models.ManyToManyField(through="users.Visit", to="reviews.company"),
        ),
    ]
