# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170704_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=30, verbose_name='miasto'),
        ),
        migrations.AddField(
            model_name='user',
            name='positions',
            field=models.CharField(blank=True, max_length=200, verbose_name='stanowiska'),
        ),
    ]
