# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 18:33
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0042_auto_20171110_1631'),
        ('users', '0008_auto_20171014_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='visited_companies',
            field=models.ManyToManyField(through='users.Visit', to='reviews.Company'),
        ),
    ]
