# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-06 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20171130_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mężczyzna')], default=None, max_length=1, verbose_name='płeć'),
        ),
    ]
