# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-07 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180106_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('K', 'Kobieta'), ('M', 'Mężczyzna')], default=None, max_length=1, null=True, verbose_name='płeć'),
        ),
    ]
