# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, choices=[('A', 'wyższe'), ('A0', 'student'), ('A1', 'MBA'), ('A2', 'stopień naukowy'), ('A3', 'inne podyplomowe'), ('B', 'średnie'), ('C', 'gimnazjalne'), ('D', 'zasadnicze'), ('E', 'podstawowe')], default=None, max_length=2, null=True, verbose_name='wykształcenie'),
        ),
    ]
