# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180120_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=True, verbose_name='Potwierdzony email'),
        ),
    ]
