# Generated by Django 5.1.3 on 2024-11-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "referer",
                    models.CharField(editable=False, max_length=200, null=True),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, editable=False, null=True, unpack_ipv4=True
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(editable=False, max_length=200, null=True),
                ),
                ("path", models.CharField(editable=False, max_length=200, null=True)),
            ],
            options={
                "verbose_name": "Próba dostępu",
                "verbose_name_plural": "Próby dostępu",
            },
        ),
        migrations.CreateModel(
            name="Benefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        blank=True, default=None, null=True, verbose_name="Zatwierdzone"
                    ),
                ),
                (
                    "reviewed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data przeglądu"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("core", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "benefit",
                "verbose_name_plural": "benefity",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        blank=True, default=None, null=True, verbose_name="Zatwierdzone"
                    ),
                ),
                (
                    "reviewed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data przeglądu"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, unique=True, verbose_name="nazwa"
                    ),
                ),
                (
                    "headquarters_city",
                    models.CharField(max_length=60, verbose_name="siedziba centrali"),
                ),
                (
                    "website",
                    models.URLField(
                        db_index=True, unique=True, verbose_name="strona www"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, verbose_name="data dodania do bazy"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="województwo"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Polska", max_length=40, verbose_name="kraj"
                    ),
                ),
                (
                    "employment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "<100"),
                            ("B", "101-500"),
                            ("C", "501-1000"),
                            ("D", "1001-5000"),
                            ("E", "5001-10000"),
                            ("F", ">10000"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="zatrudnienie",
                    ),
                ),
                (
                    "public",
                    models.BooleanField(blank=True, null=True, verbose_name="notowane"),
                ),
                (
                    "ownership",
                    models.TextField(blank=True, null=True, verbose_name="właściciele"),
                ),
                (
                    "sectors",
                    models.TextField(blank=True, null=True, verbose_name="sektory"),
                ),
                (
                    "isin",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="ISIN"
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=200, null=True)),
            ],
            options={
                "verbose_name": "Firma",
                "verbose_name_plural": "Firmy",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        blank=True, default=None, null=True, verbose_name="Zatwierdzone"
                    ),
                ),
                (
                    "reviewed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data przeglądu"
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "position",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="stanowisko"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="departament"
                    ),
                ),
                (
                    "how_got",
                    models.CharField(
                        choices=[
                            ("A", "Ogłoszenie"),
                            ("B", "Kontakty zawodowe"),
                            ("C", "Head-hunter"),
                            ("D", "Znajomi/rodzina"),
                            ("F", "Targi/prezentacje"),
                            ("G", "Strona internetowa firmy"),
                            ("H", "Inne"),
                        ],
                        default=None,
                        max_length=1,
                        verbose_name="droga do interview",
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "B. łatwo"),
                            (2, "Łatwo"),
                            (3, "Średnio"),
                            (4, "Trudno"),
                            (5, "B. trudno"),
                        ],
                        default=None,
                        verbose_name="trudność",
                    ),
                ),
                ("got_offer", models.BooleanField(verbose_name="dostał ofertę?")),
                (
                    "questions",
                    models.TextField(
                        blank=True, null=True, verbose_name="proces i pytania"
                    ),
                ),
                ("impressions", models.TextField(verbose_name="wrażenia")),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=None,
                        verbose_name="ocena",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rozmowa",
                "verbose_name_plural": "Rozmowy",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "company_linkedin_id",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("linkedin_id", models.PositiveIntegerField(blank=True, null=True)),
                ("location", models.CharField(max_length=50, null=True)),
                ("position", models.CharField(max_length=100)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "start_date_month",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "01"),
                            (2, "02"),
                            (3, "03"),
                            (4, "04"),
                            (5, "05"),
                            (6, "06"),
                            (7, "07"),
                            (8, "08"),
                            (9, "09"),
                            (10, "10"),
                            (11, "11"),
                            (12, "12"),
                        ]
                    ),
                ),
                (
                    "start_date_year",
                    models.PositiveIntegerField(
                        choices=[
                            (2024, 2024),
                            (2023, 2023),
                            (2022, 2022),
                            (2021, 2021),
                            (2020, 2020),
                            (2019, 2019),
                            (2018, 2018),
                            (2017, 2017),
                            (2016, 2016),
                            (2015, 2015),
                            (2014, 2014),
                            (2013, 2013),
                            (2012, 2012),
                            (2011, 2011),
                            (2010, 2010),
                            (2009, 2009),
                            (2008, 2008),
                            (2007, 2007),
                            (2006, 2006),
                            (2005, 2005),
                            (2004, 2004),
                            (2003, 2003),
                            (2002, 2002),
                            (2001, 2001),
                            (2000, 2000),
                            (1999, 1999),
                            (1998, 1998),
                            (1997, 1997),
                            (1996, 1996),
                            (1995, 1995),
                            (1994, 1994),
                            (1993, 1993),
                            (1992, 1992),
                            (1991, 1991),
                            (1990, 1990),
                            (1989, 1989),
                            (1988, 1988),
                            (1987, 1987),
                            (1986, 1986),
                            (1985, 1985),
                            (1984, 1984),
                            (1983, 1983),
                            (1982, 1982),
                            (1981, 1981),
                            (1980, 1980),
                            (1979, 1979),
                            (1978, 1978),
                            (1977, 1977),
                            (1976, 1976),
                            (1975, 1975),
                            (1974, 1974),
                            (1973, 1973),
                            (1972, 1972),
                            (1971, 1971),
                            (1970, 1970),
                            (1969, 1969),
                            (1968, 1968),
                            (1967, 1967),
                            (1966, 1966),
                            (1965, 1965),
                            (1964, 1964),
                            (1963, 1963),
                            (1962, 1962),
                            (1961, 1961),
                            (1960, 1960),
                        ]
                    ),
                ),
                (
                    "end_date_month",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            ("", "--"),
                            (1, "01"),
                            (2, "02"),
                            (3, "03"),
                            (4, "04"),
                            (5, "05"),
                            (6, "06"),
                            (7, "07"),
                            (8, "08"),
                            (9, "09"),
                            (10, "10"),
                            (11, "11"),
                            (12, "12"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "end_date_year",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "obecnie"),
                            (2024, 2024),
                            (2023, 2023),
                            (2022, 2022),
                            (2021, 2021),
                            (2020, 2020),
                            (2019, 2019),
                            (2018, 2018),
                            (2017, 2017),
                            (2016, 2016),
                            (2015, 2015),
                            (2014, 2014),
                            (2013, 2013),
                            (2012, 2012),
                            (2011, 2011),
                            (2010, 2010),
                            (2009, 2009),
                            (2008, 2008),
                            (2007, 2007),
                            (2006, 2006),
                            (2005, 2005),
                            (2004, 2004),
                            (2003, 2003),
                            (2002, 2002),
                            (2001, 2001),
                            (2000, 2000),
                            (1999, 1999),
                            (1998, 1998),
                            (1997, 1997),
                            (1996, 1996),
                            (1995, 1995),
                            (1994, 1994),
                            (1993, 1993),
                            (1992, 1992),
                            (1991, 1991),
                            (1990, 1990),
                            (1989, 1989),
                            (1988, 1988),
                            (1987, 1987),
                            (1986, 1986),
                            (1985, 1985),
                            (1984, 1984),
                            (1983, 1983),
                            (1982, 1982),
                            (1981, 1981),
                            (1980, 1980),
                            (1979, 1979),
                            (1978, 1978),
                            (1977, 1977),
                            (1976, 1976),
                            (1975, 1975),
                            (1974, 1974),
                            (1973, 1973),
                            (1972, 1972),
                            (1971, 1971),
                            (1970, 1970),
                            (1969, 1969),
                            (1968, 1968),
                            (1967, 1967),
                            (1966, 1966),
                            (1965, 1965),
                            (1964, 1964),
                            (1963, 1963),
                            (1962, 1962),
                            (1961, 1961),
                            (1960, 1960),
                        ],
                        default=0,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("A", "pełen etat"),
                            ("B", "część etatu"),
                            ("C", "praktyka"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stanowisko",
                "verbose_name_plural": "Stanowiska",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        blank=True, default=None, null=True, verbose_name="Zatwierdzone"
                    ),
                ),
                (
                    "reviewed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data przeglądu"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="data"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="tytuł")),
                ("pros", models.TextField(verbose_name="zalety")),
                ("cons", models.TextField(verbose_name="wady")),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="co należy zmienić"),
                ),
                (
                    "overallscore",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=None,
                        verbose_name="ocena ogólna",
                    ),
                ),
                (
                    "advancement",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=None,
                        verbose_name="możliwości rozwoju",
                    ),
                ),
                (
                    "worklife",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=None,
                        verbose_name="równowaga praca/życie",
                    ),
                ),
                (
                    "compensation",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=None,
                        verbose_name="zarobki",
                    ),
                ),
                (
                    "environment",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=None,
                        verbose_name="atmosfera w pracy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opinia",
                "verbose_name_plural": "Opinie",
            },
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        blank=True, default=None, null=True, verbose_name="Zatwierdzone"
                    ),
                ),
                (
                    "reviewed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data przeglądu"
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="data")),
                (
                    "currency",
                    models.CharField(
                        default="PLN", max_length=3, verbose_name="waluta"
                    ),
                ),
                ("salary_input", models.PositiveIntegerField(verbose_name="pensja")),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("G", "na godzinę"),
                            ("D", "dziennie"),
                            ("T", "tygodniowo"),
                            ("M", "miesięcznie"),
                            ("K", "kwartalnie"),
                            ("R", "rocznie"),
                        ],
                        default="M",
                        max_length=1,
                        verbose_name="",
                    ),
                ),
                (
                    "gross_net",
                    models.CharField(
                        choices=[("G", "brutto"), ("N", "netto")],
                        default="G",
                        max_length=1,
                        verbose_name="",
                    ),
                ),
                (
                    "bonus_input",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="premia"
                    ),
                ),
                (
                    "bonus_period",
                    models.CharField(
                        choices=[
                            ("G", "na godzinę"),
                            ("D", "dziennie"),
                            ("T", "tygodniowo"),
                            ("M", "miesięcznie"),
                            ("K", "kwartalnie"),
                            ("R", "rocznie"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="",
                    ),
                ),
                (
                    "bonus_gross_net",
                    models.CharField(
                        choices=[("G", "brutto"), ("N", "netto")],
                        default="G",
                        max_length=1,
                        verbose_name="",
                    ),
                ),
                (
                    "salary_gross_input_period",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="pensja brutto"
                    ),
                ),
                (
                    "salary_gross_annual",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="pensja brutto rocznie"
                    ),
                ),
                (
                    "bonus_gross_input_period",
                    models.PositiveIntegerField(
                        editable=False, null=True, verbose_name="premia brutto"
                    ),
                ),
                (
                    "bonus_gross_annual",
                    models.PositiveIntegerField(
                        editable=False, null=True, verbose_name="premia brutto rocznie"
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("A", "umowa o pracę"),
                            ("B", "zlecenie/umowa o dzieło"),
                            ("C", "samozatrudnienie"),
                        ],
                        default="A",
                        max_length=1,
                        verbose_name="rodzaj umowy",
                    ),
                ),
                (
                    "comments",
                    models.CharField(blank=True, max_length=200, verbose_name="uwagi"),
                ),
            ],
            options={
                "verbose_name": "Zarobki",
                "verbose_name_plural": "Zarobki",
            },
        ),
    ]
