# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 16:50
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=60)),
                ('overallscore_score', models.PositiveIntegerField(default=0, editable=False)),
                ('advancement_score', models.PositiveIntegerField(default=0, editable=False)),
                ('worklife_score', models.PositiveIntegerField(default=0, editable=False)),
                ('compensation_score', models.PositiveIntegerField(default=0, editable=False)),
                ('environment_score', models.PositiveIntegerField(default=0, editable=False)),
                ('number_of_reviews', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('years_at_company', models.PositiveIntegerField()),
                ('pros', models.CharField(max_length=500)),
                ('cons', models.CharField(max_length=500)),
                ('comment', models.TextField()),
                ('overallscore', models.PositiveIntegerField(verbose_name='ocena ogólna')),
                ('advancement', models.PositiveIntegerField(verbose_name='możliwości rozwoju')),
                ('worklife', models.PositiveIntegerField(verbose_name='równowaga praca/życie')),
                ('compensation', models.PositiveIntegerField(verbose_name='zarobki')),
                ('environment', models.PositiveIntegerField(verbose_name='atmosfera w pracy')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Company', verbose_name='recenzja firmy')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('years_at_company', models.PositiveIntegerField()),
                ('years_experience', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('m', 'm'), ('f', 'k')], editable=False, max_length=1)),
                ('date', models.DateTimeField(auto_now=True)),
                ('employment_status', models.CharField(choices=[('a', 'pełny etat - umowa na czas nieokreślony'), ('b', 'część etatu - umowa na czas nieokreślony'), ('c', 'pełny etat - umowa na czas określony'), ('d', 'część etatu - umowa na czas określony'), ('e', 'umowa zlecenie'), ('f', 'samozatrudnienie')], max_length=1)),
                ('salary', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Company')),
            ],
        ),
    ]
