# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='city',
            new_name='headquarters_city',
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(default='www.example.com'),
            preserve_default=False,
        ),
    ]
