# Generated by Django 5.1.3 on 2024-11-22 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_auto_enable_unaccent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="data dodania"),
        ),
        migrations.AlterField(
            model_name="company",
            name="headquarters_city",
            field=models.CharField(max_length=60, verbose_name="siedziba"),
        ),
        migrations.AlterField(
            model_name="company",
            name="slug",
            field=models.SlugField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name="company",
            name="website",
            field=models.URLField(
                db_index=True,
                unique=True,
                validators=[django.core.validators.URLValidator()],
                verbose_name="strona www",
            ),
        ),
    ]
