# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20170701_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='advancement_score',
            new_name='advancement_total',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='compensation_score',
            new_name='compensation_total',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='environment_score',
            new_name='environment_total',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='overallscore_score',
            new_name='number_of_reviews',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='worklife_score',
            new_name='overallscore_total',
        ),
        migrations.AddField(
            model_name='company',
            name='worklife_total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='advancement',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, verbose_name='możliwości rozwoju'),
        ),
        migrations.AlterField(
            model_name='review',
            name='compensation',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, verbose_name='zarobki'),
        ),
        migrations.AlterField(
            model_name='review',
            name='environment',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, verbose_name='atmosfera w pracy'),
        ),
        migrations.AlterField(
            model_name='review',
            name='overallscore',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, verbose_name='ocena ogólna'),
        ),
        migrations.AlterField(
            model_name='review',
            name='worklife',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, verbose_name='równowaga praca-życie'),
        ),
    ]
