# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20170701_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='employment_status',
            field=models.CharField(choices=[('a', 'Pełen etat'), ('b', 'Część etatu'), ('c', 'Zlecenie'), ('d', 'Samozazatrudnienie'), ('e', 'Inne')], default='a', max_length=1),
        ),
    ]
