# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 10:49
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0008_auto_20170704_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('years_at_company', models.PositiveIntegerField()),
                ('employment_status', models.CharField(choices=[('A', 'Pełen etat'), ('B', 'Część etatu'), ('C', 'Zlecenie'), ('D', 'Samozazatrudnienie'), ('E', 'Inne')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributed', models.BooleanField(default=False, editable=False)),
                ('sex', models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta')], max_length=1)),
                ('career_start_year', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='company',
            old_name='advancement_total',
            new_name='advancement',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='compensation_total',
            new_name='compensation',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='environment_total',
            new_name='environment',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='overallscore_total',
            new_name='overallscore',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='worklife_total',
            new_name='worklife',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='salary',
            new_name='salary_input',
        ),
        migrations.RemoveField(
            model_name='review',
            name='city',
        ),
        migrations.RemoveField(
            model_name='review',
            name='company',
        ),
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='position',
        ),
        migrations.RemoveField(
            model_name='review',
            name='years_at_company',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='city',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='company',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='id',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='position',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='years_at_company',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='years_experience',
        ),
        migrations.AddField(
            model_name='salary',
            name='base_annual',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='salary',
            name='base_monthly',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='salary',
            name='bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salary',
            name='currency',
            field=models.CharField(default='PLN', max_length=3),
        ),
        migrations.AddField(
            model_name='salary',
            name='gross_net',
            field=models.CharField(choices=[('G', 'Brutto'), ('N', 'Netto')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='salary',
            name='gross_net_bonus',
            field=models.CharField(choices=[('G', 'Brutto'), ('N', 'Netto')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='salary',
            name='time_unit',
            field=models.CharField(choices=[('M', 'miesięcznie'), ('R', 'rocznie'), ('G', 'na godzinę')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='salary',
            name='time_unit_bonus',
            field=models.CharField(choices=[('M', 'miesięcznie'), ('R', 'rocznie'), ('G', 'na godzinę')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='salary',
            name='total_annual',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='salary',
            name='total_monthly',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='position',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Company'),
        ),
        migrations.AddField(
            model_name='position',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='position_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reviews.Position'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='position_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reviews.Position'),
            preserve_default=False,
        ),
    ]
