# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_auto_20170819_2052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Positions',
            new_name='Job',
        ),
    ]
