# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_auto_20170824_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='Polska', max_length=40, verbose_name='kraj'),
        ),
        migrations.AddField(
            model_name='company',
            name='employment',
            field=models.CharField(blank=True, choices=[('A', '<100'), ('B', '101-500'), ('C', '501-1000'), ('D', '1001-5000'), ('E', '5001-10000'), ('F', '>10000')], max_length=1, null=True, verbose_name='zatrudnienie'),
        ),
        migrations.AddField(
            model_name='company',
            name='ownership',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='właściciele'),
        ),
        migrations.AddField(
            model_name='company',
            name='public',
            field=models.NullBooleanField(verbose_name='notowane'),
        ),
        migrations.AddField(
            model_name='company',
            name='region',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='województwo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career_start_year',
            field=models.PositiveIntegerField(blank=True, choices=[(2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971)], null=True, verbose_name='rok rozpoczęcia kariery'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mężczyzna')], default='K', max_length=1, null=True, verbose_name='płeć'),
        ),
    ]
