# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_auto_20170906_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='overallscore',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, verbose_name='ocena og&oacute;lna'),
        ),
        migrations.AlterField(
            model_name='review',
            name='worklife',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, verbose_name='r&oacute;wnowaga praca/życie'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='bonus_gross_net',
            field=models.CharField(blank=True, choices=[('G', 'brutto'), ('N', 'netto')], default='G', max_length=1, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='salary',
            name='bonus_period',
            field=models.CharField(blank=True, choices=[('M', 'miesięcznie'), ('K', 'kwartalnie'), ('R', 'rocznie'), ('G', 'na godzinę')], default='R', max_length=1, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='salary',
            name='gross_net',
            field=models.CharField(blank=True, choices=[('G', 'brutto'), ('N', 'netto')], default='G', max_length=1, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='salary',
            name='period',
            field=models.CharField(blank=True, choices=[('M', 'miesięcznie'), ('K', 'kwartalnie'), ('R', 'rocznie'), ('G', 'na godzinę')], default='M', max_length=1, verbose_name=''),
        ),
    ]
