# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0022_auto_20170908_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='company_linkedin_id',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mężczyzna')], default=None, max_length=1, null=True, verbose_name='płeć'),
        ),
    ]
