# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 20:37
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0025_auto_20171004_1819'),
    ]

    operations = [
        UnaccentExtension()
    ]
