# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0027_auto_20171008_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Firma', 'verbose_name_plural': 'Firmy'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Stanowisko', 'verbose_name_plural': 'Stanowiska'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Recenzja', 'verbose_name_plural': 'Recenzje'},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name': 'Zarobki', 'verbose_name_plural': 'Zarobki'},
        ),
    ]
