# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-13 22:49
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0028_auto_20171009_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_reviews',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Liczba ocen'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(blank=True, max_length=500, verbose_name='co należy zmienić'),
        ),
        migrations.AlterField(
            model_name='review',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Company', verbose_name='firma'),
        ),
        migrations.AlterField(
            model_name='review',
            name='cons',
            field=models.CharField(max_length=500, verbose_name='wady'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='review',
            name='overallscore',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, verbose_name='ocena ogólna'),
        ),
        migrations.AlterField(
            model_name='review',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Position', verbose_name='stanowisko'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pros',
            field=models.CharField(max_length=500, verbose_name='zalety'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=100, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='review',
            name='worklife',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, verbose_name='równowaga praca/życie'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
