# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-13 23:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0029_auto_20171014_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='got_offer',
            field=models.NullBooleanField(choices=[(True, 'Tak'), (False, 'Nie')], default=None, verbose_name='czy dostał ofertę'),
        ),
        migrations.AlterField(
            model_name='review',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='reviews.Company', verbose_name='firma'),
        ),
        migrations.AlterField(
            model_name='review',
            name='position',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Position', verbose_name='stanowisko'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='base_annual',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, verbose_name='Pensja zasadnicza rocznie'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='base_monthly',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, verbose_name='Pensja zasadnicza miesięcznie'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='reviews.Company', verbose_name='firma'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='position',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Position', verbose_name='stanowisko'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_annual',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, verbose_name='Pensja całkowita rocznie'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_monthly',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, verbose_name='Pensja całkowita miesięcznie'),
        ),
    ]
