# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-14 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0030_auto_20171014_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='approved',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='approved',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='approved',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salary',
            name='approved',
            field=models.NullBooleanField(default=False),
        ),
    ]
