# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-14 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0031_auto_20171014_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interview',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salary',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
