# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 23:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0034_auto_20171014_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data dodania do bazy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='reviewed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data przeglądu'),
        ),
        migrations.AddField(
            model_name='interview',
            name='reviewed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data przeglądu'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data przeglądu'),
        ),
        migrations.AddField(
            model_name='salary',
            name='reviewed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data przeglądu'),
        ),
        migrations.AlterField(
            model_name='company',
            name='approved',
            field=models.NullBooleanField(default=None, verbose_name='Zatwierdzone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='reviewer',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Zatwierdzający'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='approved',
            field=models.NullBooleanField(default=None, verbose_name='Zatwierdzone'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='reviewer',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Zatwierdzający'),
        ),
        migrations.AlterField(
            model_name='position',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.NullBooleanField(default=None, verbose_name='Zatwierdzone'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Zatwierdzający'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='approved',
            field=models.NullBooleanField(default=None, verbose_name='Zatwierdzone'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='reviewer',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Zatwierdzający'),
        ),
    ]
