# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0035_auto_20171021_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, verbose_name='Ocena'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='got_offer',
            field=models.NullBooleanField(choices=[(True, 'Tak'), (False, 'Nie'), (None, 'Nieznane')], default=None, verbose_name='czy dostał ofertę'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='impressions',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='wrażenia'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='questions',
            field=models.TextField(blank=True, null=True, verbose_name='pytania'),
        ),
    ]
