# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0036_auto_20171021_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='impressions',
            field=models.TextField(blank=True, null=True, verbose_name='wrażenia'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, verbose_name='co należy zmienić'),
        ),
        migrations.AlterField(
            model_name='review',
            name='cons',
            field=models.TextField(verbose_name='wady'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pros',
            field=models.TextField(verbose_name='zalety'),
        ),
    ]
