# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0037_auto_20171022_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='difficulty',
            field=models.PositiveIntegerField(choices=[(1, 'B. łatwo'), (2, 'Łatwo'), (3, 'Średnio'), (4, 'Trudno'), (5, 'B. trudno')], default=None, verbose_name='trudność'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='got_offer',
            field=models.BooleanField(choices=[(True, 'Tak'), (False, 'Nie')], default=None, verbose_name='czy dostał ofertę'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='how_got',
            field=models.CharField(choices=[('A', 'Ogłoszenie'), ('B', 'Kontakty profesjonalne'), ('C', 'Head-hunter'), ('D', 'Znajomi-rodzina'), ('E', 'Seks z decydentem'), ('F', 'Targi/prezentacje'), ('F', 'Inne')], default=None, max_length=1, verbose_name='droga do interview'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='position',
            field=models.CharField(max_length=100, verbose_name='stanowisko'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='bonus_input',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='premia'),
        ),
    ]
