# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0038_auto_20171023_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='got_offer',
            field=models.BooleanField(verbose_name='dostał ofertę'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='impressions',
            field=models.TextField(default='Bardzo pozytywne wrażenia', verbose_name='wrażenia'),
            preserve_default=False,
        ),
    ]
