# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0040_auto_20171110_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
