# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0041_auto_20171110_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='data dodania do bazy'),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, null=True),
        ),
    ]
