# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0042_auto_20171110_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employment',
            field=models.CharField(blank=True, choices=[('A', '<100'), ('B', '101-500'), ('C', '501-1000'), ('D', '1001-5000'), ('E', '5001-10000'), ('F', '>10000'), ('G', 'n/a')], max_length=1, null=True, verbose_name='zatrudnienie'),
        ),
    ]
