# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0043_auto_20171130_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ISIN'),
        ),
        migrations.AddField(
            model_name='company',
            name='products',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Produkty'),
        ),
        migrations.AddField(
            model_name='company',
            name='sectors',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='sektory'),
        ),
        migrations.AlterField(
            model_name='company',
            name='employment',
            field=models.CharField(blank=True, choices=[('A', '<100'), ('B', '101-500'), ('C', '501-1000'), ('D', '1001-5000'), ('E', '5001-10000'), ('F', '>10000')], max_length=1, null=True, verbose_name='zatrudnienie'),
        ),
    ]
