# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0046_auto_20171201_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='nazwa'),
        ),
    ]
