# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0050_auto_20171201_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ownership',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='właściciele'),
        ),
    ]
