# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0052_auto_20171201_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, null=True),
        ),
    ]
