# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0053_auto_20171201_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sectors',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='sektory'),
        ),
    ]
