# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-02 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0054_auto_20171201_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ownership',
            field=models.TextField(blank=True, null=True, verbose_name='właściciele'),
        ),
    ]
