# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-04 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0055_auto_20180102_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='salary_input_gross',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='pensja brutto'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='bonus_period',
            field=models.CharField(choices=[('G', 'na godzinę'), ('D', 'dziennie'), ('M', 'miesięcznie'), ('K', 'kwartalnie'), ('R', 'rocznie')], default='R', max_length=1, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='salary',
            name='period',
            field=models.CharField(choices=[('G', 'na godzinę'), ('D', 'dziennie'), ('M', 'miesięcznie'), ('K', 'kwartalnie'), ('R', 'rocznie')], default='M', max_length=1, verbose_name=''),
        ),
    ]
