# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-04 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0056_auto_20180104_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='bonus_anual',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='premia rocznie'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, verbose_name='ocena'),
        ),
    ]
