# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-25 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0057_auto_20171223_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='company_linkedin_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
