# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-05 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0058_auto_20180105_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='bonus_gross_anual',
            new_name='bonus_gross_annual',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='salary_gross_anual',
            new_name='salary_gross_annual',
        ),
    ]
