# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-11 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0062_auto_20180108_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='comments',
            field=models.CharField(blank=True, max_length=200, verbose_name='uwagi'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='bonus_period',
            field=models.CharField(choices=[('G', 'na godzinę'), ('D', 'dziennie'), ('T', 'tygodniowo'), ('M', 'miesięcznie'), ('K', 'kwartalnie'), ('R', 'rocznie')], default='R', max_length=1, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='salary',
            name='contract_type',
            field=models.CharField(choices=[('A', 'umowa o pracę'), ('B', 'zlecenie/umowa o dzieło'), ('C', 'samozatrudnienie')], default='A', max_length=1, verbose_name='rodzaj umowy'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='period',
            field=models.CharField(choices=[('G', 'na godzinę'), ('D', 'dziennie'), ('T', 'tygodniowo'), ('M', 'miesięcznie'), ('K', 'kwartalnie'), ('R', 'rocznie')], default='M', max_length=1, verbose_name=''),
        ),
    ]
