# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-11 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0063_auto_20180111_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.NullBooleanField(default=None, verbose_name='Zatwierdzone')),
                ('reviewed_date', models.DateField(blank=True, null=True, verbose_name='Data przeglądu')),
                ('name', models.CharField(max_length=100)),
                ('core', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Zatwierdzający')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='salary',
            name='benefits',
            field=models.ManyToManyField(to='reviews.Benefit'),
        ),
    ]
