# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-11 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0064_auto_20180111_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'benefit', 'verbose_name_plural': 'benefity'},
        ),
        migrations.AddField(
            model_name='benefit',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.Company', verbose_name='firma'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='how_got',
            field=models.CharField(choices=[('A', 'Ogłoszenie'), ('B', 'Kontakty zawodowe'), ('C', 'Head-hunter'), ('D', 'Znajomi/rodzina'), ('E', 'Seks z decydentem'), ('F', 'Targi/prezentacje'), ('G', 'Strona internetowa firmy'), ('H', 'Inne')], default=None, max_length=1, verbose_name='droga do interview'),
        ),
        migrations.AlterField(
            model_name='position',
            name='employment_status',
            field=models.CharField(choices=[('A', 'pełen etat'), ('B', 'część etatu'), ('C', 'praktyka')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='salary',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='reviews.Benefit', verbose_name='benefity'),
        ),
    ]
