# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-13 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0065_auto_20180111_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='source',
        ),
        migrations.AlterField(
            model_name='benefit',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
