# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0069_auto_20180117_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='position',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Position', verbose_name='stanowisko'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='position',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Position', verbose_name='stanowisko'),
        ),
    ]
