# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 20:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0071_interview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interview',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.Company'),
        ),
        migrations.AlterField(
            model_name='position',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='position',
            field=models.OneToOneField(default=2, editable=False, on_delete=django.db.models.deletion.CASCADE, to='reviews.Position', verbose_name='stanowisko'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salary',
            name='position',
            field=models.OneToOneField(default=2, editable=False, on_delete=django.db.models.deletion.CASCADE, to='reviews.Position', verbose_name='stanowisko'),
            preserve_default=False,
        ),
    ]
