# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0073_auto_20180118_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='bonus_period',
            field=models.CharField(choices=[('G', 'na godzinę'), ('D', 'dziennie'), ('T', 'tygodniowo'), ('M', 'miesięcznie'), ('K', 'kwartalnie'), ('R', 'rocznie')], max_length=1, null=True, verbose_name=''),
        ),
    ]
