# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-13 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0074_auto_20180120_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(db_index=True, unique=True, verbose_name='strona www'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='position',
            field=models.CharField(db_index=True, max_length=100, verbose_name='stanowisko'),
        ),
        migrations.AlterField(
            model_name='position',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['position', 'company'], name='reviews_pos_positio_35f801_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['user', 'company'], name='reviews_pos_user_id_20cf89_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['company', 'position'], name='reviews_sal_company_c3c707_idx'),
        ),
    ]
