# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-16 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0076_auto_20180224_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('referer', models.CharField(editable=False, max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, editable=False, null=True, unpack_ipv4=True)),
                ('user_agent', models.CharField(editable=False, max_length=100)),
                ('path', models.CharField(editable=False, max_length=100)),
            ],
            options={
                'verbose_name': 'Próba dostępu',
                'verbose_name_plural': 'Próby dostępu',
            },
        ),
    ]
