# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-16 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0077_accessattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessattempt',
            name='path',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='accessattempt',
            name='referer',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='accessattempt',
            name='user_agent',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
